name: casarancha
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audio_waveforms: ^1.3.0
  cached_network_image: ^3.4.1
  cherry_toast: ^1.13.0
  chewie: ^1.12.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  dot_curved_bottom_nav: ^0.0.2
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_file_dialog: ^3.0.2
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_polls: ^0.1.6
  flutter_reaction_button: ^3.0.0+3
  flutter_secure_storage: ^9.2.4
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.12.0
  get: ^4.7.2
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.1.1
  http: ^1.4.0
  http_parser: ^4.1.2
  # image_gallery_saver: ^2.0.3
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  loading_indicator: ^3.1.1
  lottie: ^3.3.1
  lucide_icons_flutter: ^3.0.7
  mime: ^2.0.0
  onesignal_flutter: ^5.3.4
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pinput: ^5.0.1
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  socket_io_client: ^3.1.2
  uuid: ^4.5.1
  video_compress: ^3.1.4
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/loogo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/icons/
